# Generated by Django 4.0.4 on 2022-04-22 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo do Projeto')),
                ('dataInicio', models.DateTimeField(auto_now_add=True, verbose_name='Data Inicial')),
                ('atualiza', models.DateTimeField(auto_now=True)),
                ('dataLimite', models.DateField(verbose_name='Data Limite')),
                ('descreva', models.TextField(verbose_name='Descreva o Projeto')),
                ('status', models.CharField(choices=[('P', 'Projeto postado'), ('F', 'Em andamento'), ('E', 'Realizados')], max_length=1, null=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Empresa', to='usuarios.empresa')),
            ],
        ),
    ]
